// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assignment struct {
	ID          pgtype.UUID        `json:"id"`
	PersonID    pgtype.UUID        `json:"person_id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	StartDate   pgtype.Date        `json:"start_date"`
	EndDate     pgtype.Date        `json:"end_date"`
	HoursPerDay pgtype.Numeric     `json:"hours_per_day"`
	Notes       string             `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	DiffJson    []byte             `json:"diff_json"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Milestone struct {
	ID        pgtype.UUID        `json:"id"`
	ProjectID pgtype.UUID        `json:"project_id"`
	PhaseID   pgtype.UUID        `json:"phase_id"`
	Name      string             `json:"name"`
	Date      pgtype.Date        `json:"date"`
	EndDate   pgtype.Date        `json:"end_date"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Phase struct {
	ID                pgtype.UUID        `json:"id"`
	ProjectID         pgtype.UUID        `json:"project_id"`
	Name              string             `json:"name"`
	Color             string             `json:"color"`
	Notes             string             `json:"notes"`
	StartDate         pgtype.Date        `json:"start_date"`
	EndDate           pgtype.Date        `json:"end_date"`
	BudgetTotal       pgtype.Numeric     `json:"budget_total"`
	DefaultHourlyRate pgtype.Numeric     `json:"default_hourly_rate"`
	Billable          bool               `json:"billable"`
	Status            int16              `json:"status"`
	ArchivedAt        pgtype.Timestamptz `json:"archived_at"`
	FloatID           pgtype.Int8        `json:"float_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Person struct {
	ID                  pgtype.UUID        `json:"id"`
	Name                string             `json:"name"`
	Email               string             `json:"email"`
	Role                string             `json:"role"`
	WeeklyCapacityHours pgtype.Numeric     `json:"weekly_capacity_hours"`
	ArchivedAt          pgtype.Timestamptz `json:"archived_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	UserID              pgtype.UUID        `json:"user_id"`
}

type Project struct {
	ID         pgtype.UUID        `json:"id"`
	Name       string             `json:"name"`
	Client     string             `json:"client"`
	Color      string             `json:"color"`
	Notes      string             `json:"notes"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	Billable   bool               `json:"billable"`
}

type TimeOff struct {
	ID        pgtype.UUID        `json:"id"`
	PersonID  pgtype.UUID        `json:"person_id"`
	StartDate pgtype.Date        `json:"start_date"`
	EndDate   pgtype.Date        `json:"end_date"`
	Type      string             `json:"type"`
	Notes     string             `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Sub       string             `json:"sub"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	Role      string             `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
