// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archivePerson = `-- name: ArchivePerson :one
UPDATE people
SET archived_at = now(), updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING id, name, email, role, weekly_capacity_hours, archived_at, created_at, updated_at, user_id
`

func (q *Queries) ArchivePerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, archivePerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.WeeklyCapacityHours,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const projectSelectCols = `id, name, client, color, notes, archived_at, created_at, updated_at, billable, budget_type, budget_total, budget_priority, tags, project_code`

func scanProject(scanner interface {
	Scan(dest ...any) error
}) (Project, error) {
	var p Project
	err := scanner.Scan(
		&p.ID,
		&p.Name,
		&p.Client,
		&p.Color,
		&p.Notes,
		&p.ArchivedAt,
		&p.CreatedAt,
		&p.UpdatedAt,
		&p.Billable,
		&p.BudgetType,
		&p.BudgetTotal,
		&p.BudgetPriority,
		&p.Tags,
		&p.ProjectCode,
	)
	return p, err
}

const archiveProject = `-- name: ArchiveProject :one
UPDATE projects
SET archived_at = now(), updated_at = now()
WHERE id = $1 AND archived_at IS NULL
RETURNING ` + projectSelectCols

func (q *Queries) ArchiveProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, archiveProject, id)
	return scanProject(row)
}

const createAssignment = `-- name: CreateAssignment :one
INSERT INTO assignments (person_id, project_id, start_date, end_date, hours_per_day, notes)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, person_id, project_id, start_date, end_date, hours_per_day, notes, created_at, updated_at
`

type CreateAssignmentParams struct {
	PersonID    pgtype.UUID    `json:"person_id"`
	ProjectID   pgtype.UUID    `json:"project_id"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	HoursPerDay pgtype.Numeric `json:"hours_per_day"`
	Notes       string         `json:"notes"`
}

func (q *Queries) CreateAssignment(ctx context.Context, arg CreateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, createAssignment,
		arg.PersonID,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HoursPerDay,
		arg.Notes,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ProjectID,
		&i.StartDate,
		&i.EndDate,
		&i.HoursPerDay,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMilestone = `-- name: CreateMilestone :one
INSERT INTO milestones (project_id, phase_id, name, date, end_date)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, phase_id, name, date, end_date, created_at, updated_at
`

type CreateMilestoneParams struct {
	ProjectID pgtype.UUID `json:"project_id"`
	PhaseID   pgtype.UUID `json:"phase_id"`
	Name      string      `json:"name"`
	Date      pgtype.Date `json:"date"`
	EndDate   pgtype.Date `json:"end_date"`
}

func (q *Queries) CreateMilestone(ctx context.Context, arg CreateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, createMilestone,
		arg.ProjectID,
		arg.PhaseID,
		arg.Name,
		arg.Date,
		arg.EndDate,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PhaseID,
		&i.Name,
		&i.Date,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (name, email, role, weekly_capacity_hours)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, role, weekly_capacity_hours, archived_at, created_at, updated_at, user_id
`

type CreatePersonParams struct {
	Name                string         `json:"name"`
	Email               string         `json:"email"`
	Role                string         `json:"role"`
	WeeklyCapacityHours pgtype.Numeric `json:"weekly_capacity_hours"`
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, createPerson,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.WeeklyCapacityHours,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.WeeklyCapacityHours,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (name, client, color, notes, billable, budget_type, budget_total, budget_priority, tags, project_code)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING ` + projectSelectCols

type CreateProjectParams struct {
	Name           string         `json:"name"`
	Client         string         `json:"client"`
	Color          string         `json:"color"`
	Notes          string         `json:"notes"`
	Billable       bool           `json:"billable"`
	BudgetType     pgtype.Int2    `json:"budget_type"`
	BudgetTotal    pgtype.Numeric `json:"budget_total"`
	BudgetPriority pgtype.Int2    `json:"budget_priority"`
	Tags           []string       `json:"tags"`
	ProjectCode    pgtype.Text    `json:"project_code"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Client,
		arg.Color,
		arg.Notes,
		arg.Billable,
		arg.BudgetType,
		arg.BudgetTotal,
		arg.BudgetPriority,
		arg.Tags,
		arg.ProjectCode,
	)
	return scanProject(row)
}

const createTimeOff = `-- name: CreateTimeOff :one
INSERT INTO time_off (person_id, start_date, end_date, type, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, person_id, start_date, end_date, type, notes, created_at, updated_at
`

type CreateTimeOffParams struct {
	PersonID  pgtype.UUID `json:"person_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Type      string      `json:"type"`
	Notes     string      `json:"notes"`
}

func (q *Queries) CreateTimeOff(ctx context.Context, arg CreateTimeOffParams) (TimeOff, error) {
	row := q.db.QueryRow(ctx, createTimeOff,
		arg.PersonID,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Notes,
	)
	var i TimeOff
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAssignment = `-- name: DeleteAssignment :exec
DELETE FROM assignments WHERE id = $1
`

func (q *Queries) DeleteAssignment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAssignment, id)
	return err
}

const deleteMilestone = `-- name: DeleteMilestone :exec
DELETE FROM milestones WHERE id = $1
`

func (q *Queries) DeleteMilestone(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMilestone, id)
	return err
}

const deleteTimeOff = `-- name: DeleteTimeOff :exec
DELETE FROM time_off WHERE id = $1
`

func (q *Queries) DeleteTimeOff(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeOff, id)
	return err
}

const ensurePersonForUser = `-- name: EnsurePersonForUser :exec
INSERT INTO people (user_id, name, email, weekly_capacity_hours)
VALUES ($1, $2, $3, 40)
ON CONFLICT (user_id) DO NOTHING
`

type EnsurePersonForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   string      `json:"name"`
	Email  string      `json:"email"`
}

func (q *Queries) EnsurePersonForUser(ctx context.Context, arg EnsurePersonForUserParams) error {
	_, err := q.db.Exec(ctx, ensurePersonForUser, arg.UserID, arg.Name, arg.Email)
	return err
}

const getAssignment = `-- name: GetAssignment :one
SELECT id, person_id, project_id, start_date, end_date, hours_per_day, notes, created_at, updated_at FROM assignments WHERE id = $1
`

func (q *Queries) GetAssignment(ctx context.Context, id pgtype.UUID) (Assignment, error) {
	row := q.db.QueryRow(ctx, getAssignment, id)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ProjectID,
		&i.StartDate,
		&i.EndDate,
		&i.HoursPerDay,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMilestone = `-- name: GetMilestone :one
SELECT id, project_id, phase_id, name, date, end_date, created_at, updated_at FROM milestones WHERE id = $1
`

func (q *Queries) GetMilestone(ctx context.Context, id pgtype.UUID) (Milestone, error) {
	row := q.db.QueryRow(ctx, getMilestone, id)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PhaseID,
		&i.Name,
		&i.Date,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, email, role, weekly_capacity_hours, archived_at, created_at, updated_at, user_id FROM people WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.WeeklyCapacityHours,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT ` + projectSelectCols + ` FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	return scanProject(row)
}

const getTimeOff = `-- name: GetTimeOff :one
SELECT id, person_id, start_date, end_date, type, notes, created_at, updated_at FROM time_off WHERE id = $1
`

func (q *Queries) GetTimeOff(ctx context.Context, id pgtype.UUID) (TimeOff, error) {
	row := q.db.QueryRow(ctx, getTimeOff, id)
	var i TimeOff
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySub = `-- name: GetUserBySub :one
SELECT id, sub, email, name, role, created_at, updated_at FROM users WHERE sub = $1
`

func (q *Queries) GetUserBySub(ctx context.Context, sub string) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySub, sub)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssignmentsInRange = `-- name: ListAssignmentsInRange :many

SELECT a.id, a.person_id, a.project_id, a.start_date, a.end_date, a.hours_per_day, a.notes, a.created_at, a.updated_at
FROM assignments a
WHERE a.start_date <= $1::date
  AND a.end_date >= $2::date
ORDER BY a.start_date ASC, a.id ASC
`

type ListAssignmentsInRangeParams struct {
	ToDate   pgtype.Date `json:"to_date"`
	FromDate pgtype.Date `json:"from_date"`
}

// ===== assignments =====
func (q *Queries) ListAssignmentsInRange(ctx context.Context, arg ListAssignmentsInRangeParams) ([]Assignment, error) {
	rows, err := q.db.Query(ctx, listAssignmentsInRange, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assignment
	for rows.Next() {
		var i Assignment
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.ProjectID,
			&i.StartDate,
			&i.EndDate,
			&i.HoursPerDay,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMilestonesByProject = `-- name: ListMilestonesByProject :many

SELECT id, project_id, phase_id, name, date, end_date, created_at, updated_at FROM milestones
WHERE project_id = $1
ORDER BY date ASC, id ASC
`

// ===== milestones =====
func (q *Queries) ListMilestonesByProject(ctx context.Context, projectID pgtype.UUID) ([]Milestone, error) {
	rows, err := q.db.Query(ctx, listMilestonesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Milestone
	for rows.Next() {
		var i Milestone
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.PhaseID,
			&i.Name,
			&i.Date,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeople = `-- name: ListPeople :many

SELECT id, name, email, role, weekly_capacity_hours, archived_at, created_at, updated_at, user_id FROM people
WHERE
    ($1::boolean OR archived_at IS NULL)
ORDER BY name ASC
`

// ===== people =====
func (q *Queries) ListPeople(ctx context.Context, includeArchived bool) ([]Person, error) {
	rows, err := q.db.Query(ctx, listPeople, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.WeeklyCapacityHours,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many

SELECT ` + projectSelectCols + ` FROM projects
WHERE
    ($1::boolean OR archived_at IS NULL)
ORDER BY name ASC
`

// ===== projects =====
func (q *Queries) ListProjects(ctx context.Context, includeArchived bool) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects, includeArchived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		p, err := scanProject(rows)
		if err != nil {
			return nil, err
		}
		items = append(items, p)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTimeOffInRange = `-- name: ListTimeOffInRange :many

SELECT t.id, t.person_id, t.start_date, t.end_date, t.type, t.notes, t.created_at, t.updated_at
FROM time_off t
WHERE t.start_date <= $1::date
  AND t.end_date   >= $2::date
ORDER BY t.start_date ASC, t.id ASC
`

type ListTimeOffInRangeParams struct {
	ToDate   pgtype.Date `json:"to_date"`
	FromDate pgtype.Date `json:"from_date"`
}

// ===== time_off =====
func (q *Queries) ListTimeOffInRange(ctx context.Context, arg ListTimeOffInRangeParams) ([]TimeOff, error) {
	rows, err := q.db.Query(ctx, listTimeOffInRange, arg.ToDate, arg.FromDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeOff
	for rows.Next() {
		var i TimeOff
		if err := rows.Scan(
			&i.ID,
			&i.PersonID,
			&i.StartDate,
			&i.EndDate,
			&i.Type,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unarchivePerson = `-- name: UnarchivePerson :one
UPDATE people
SET archived_at = NULL, updated_at = now()
WHERE id = $1
RETURNING id, name, email, role, weekly_capacity_hours, archived_at, created_at, updated_at, user_id
`

func (q *Queries) UnarchivePerson(ctx context.Context, id pgtype.UUID) (Person, error) {
	row := q.db.QueryRow(ctx, unarchivePerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.WeeklyCapacityHours,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const unarchiveProject = `-- name: UnarchiveProject :one
UPDATE projects
SET archived_at = NULL, updated_at = now()
WHERE id = $1
RETURNING ` + projectSelectCols

func (q *Queries) UnarchiveProject(ctx context.Context, id pgtype.UUID) (Project, error) {
	row := q.db.QueryRow(ctx, unarchiveProject, id)
	return scanProject(row)
}

const updateAssignment = `-- name: UpdateAssignment :one
UPDATE assignments
SET person_id     = $2,
    project_id    = $3,
    start_date    = $4,
    end_date      = $5,
    hours_per_day = $6,
    notes         = $7,
    updated_at    = now()
WHERE id = $1
RETURNING id, person_id, project_id, start_date, end_date, hours_per_day, notes, created_at, updated_at
`

type UpdateAssignmentParams struct {
	ID          pgtype.UUID    `json:"id"`
	PersonID    pgtype.UUID    `json:"person_id"`
	ProjectID   pgtype.UUID    `json:"project_id"`
	StartDate   pgtype.Date    `json:"start_date"`
	EndDate     pgtype.Date    `json:"end_date"`
	HoursPerDay pgtype.Numeric `json:"hours_per_day"`
	Notes       string         `json:"notes"`
}

func (q *Queries) UpdateAssignment(ctx context.Context, arg UpdateAssignmentParams) (Assignment, error) {
	row := q.db.QueryRow(ctx, updateAssignment,
		arg.ID,
		arg.PersonID,
		arg.ProjectID,
		arg.StartDate,
		arg.EndDate,
		arg.HoursPerDay,
		arg.Notes,
	)
	var i Assignment
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.ProjectID,
		&i.StartDate,
		&i.EndDate,
		&i.HoursPerDay,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMilestone = `-- name: UpdateMilestone :one
UPDATE milestones
SET phase_id = $2,
    name = $3,
    date = $4,
    end_date = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, project_id, phase_id, name, date, end_date, created_at, updated_at
`

type UpdateMilestoneParams struct {
	ID      pgtype.UUID `json:"id"`
	PhaseID pgtype.UUID `json:"phase_id"`
	Name    string      `json:"name"`
	Date    pgtype.Date `json:"date"`
	EndDate pgtype.Date `json:"end_date"`
}

func (q *Queries) UpdateMilestone(ctx context.Context, arg UpdateMilestoneParams) (Milestone, error) {
	row := q.db.QueryRow(ctx, updateMilestone,
		arg.ID,
		arg.PhaseID,
		arg.Name,
		arg.Date,
		arg.EndDate,
	)
	var i Milestone
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.PhaseID,
		&i.Name,
		&i.Date,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePerson = `-- name: UpdatePerson :one
UPDATE people
SET name = $2,
    email = $3,
    role = $4,
    weekly_capacity_hours = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, name, email, role, weekly_capacity_hours, archived_at, created_at, updated_at, user_id
`

type UpdatePersonParams struct {
	ID                  pgtype.UUID    `json:"id"`
	Name                string         `json:"name"`
	Email               string         `json:"email"`
	Role                string         `json:"role"`
	WeeklyCapacityHours pgtype.Numeric `json:"weekly_capacity_hours"`
}

func (q *Queries) UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error) {
	row := q.db.QueryRow(ctx, updatePerson,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Role,
		arg.WeeklyCapacityHours,
	)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.WeeklyCapacityHours,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
	)
	return i, err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name            = $2,
    client          = $3,
    color           = $4,
    notes           = $5,
    billable        = $6,
    budget_type     = $7,
    budget_total    = $8,
    budget_priority = $9,
    tags            = $10,
    project_code    = $11,
    updated_at      = now()
WHERE id = $1
RETURNING ` + projectSelectCols

type UpdateProjectParams struct {
	ID             pgtype.UUID    `json:"id"`
	Name           string         `json:"name"`
	Client         string         `json:"client"`
	Color          string         `json:"color"`
	Notes          string         `json:"notes"`
	Billable       bool           `json:"billable"`
	BudgetType     pgtype.Int2    `json:"budget_type"`
	BudgetTotal    pgtype.Numeric `json:"budget_total"`
	BudgetPriority pgtype.Int2    `json:"budget_priority"`
	Tags           []string       `json:"tags"`
	ProjectCode    pgtype.Text    `json:"project_code"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Client,
		arg.Color,
		arg.Notes,
		arg.Billable,
		arg.BudgetType,
		arg.BudgetTotal,
		arg.BudgetPriority,
		arg.Tags,
		arg.ProjectCode,
	)
	return scanProject(row)
}

const updateTimeOff = `-- name: UpdateTimeOff :one
UPDATE time_off
SET person_id = $2,
    start_date = $3,
    end_date = $4,
    type = $5,
    notes = $6,
    updated_at = now()
WHERE id = $1
RETURNING id, person_id, start_date, end_date, type, notes, created_at, updated_at
`

type UpdateTimeOffParams struct {
	ID        pgtype.UUID `json:"id"`
	PersonID  pgtype.UUID `json:"person_id"`
	StartDate pgtype.Date `json:"start_date"`
	EndDate   pgtype.Date `json:"end_date"`
	Type      string      `json:"type"`
	Notes     string      `json:"notes"`
}

func (q *Queries) UpdateTimeOff(ctx context.Context, arg UpdateTimeOffParams) (TimeOff, error) {
	row := q.db.QueryRow(ctx, updateTimeOff,
		arg.ID,
		arg.PersonID,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.Notes,
	)
	var i TimeOff
	err := row.Scan(
		&i.ID,
		&i.PersonID,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (sub, email, name, role)
VALUES ($1, $2, $3, $4)
ON CONFLICT (sub) DO UPDATE SET
    email = EXCLUDED.email,
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    updated_at = now()
RETURNING id, sub, email, name, role, created_at, updated_at
`

type UpsertUserParams struct {
	Sub   string `json:"sub"`
	Email string `json:"email"`
	Name  string `json:"name"`
	Role  string `json:"role"`
}

// ===== users =====
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Sub,
		arg.Email,
		arg.Name,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Sub,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
